# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_kernel <- function(connection_file) {
    .Call('_JuniperKernel_init_kernel', PACKAGE = 'JuniperKernel', connection_file)
}

boot_kernel <- function(kernel, interrupt_event) {
    .Call('_JuniperKernel_boot_kernel', PACKAGE = 'JuniperKernel', kernel, interrupt_event)
}

#' The XMock
#'
#' Get the xeus mock interpreter for interoperability with other
#' projects.
#'
#' @author Spencer Aiello
#'
#' @export
the_xmock <- function() {
    .Call('_JuniperKernel_the_xmock', PACKAGE = 'JuniperKernel')
}

sock_recv <- function(kernel, sockName) {
    .Call('_JuniperKernel_sock_recv', PACKAGE = 'JuniperKernel', kernel, sockName)
}

post_handle <- function(kernel, res, sockName) {
    invisible(.Call('_JuniperKernel_post_handle', PACKAGE = 'JuniperKernel', kernel, res, sockName))
}

rebroadcast_input <- function(kernel, execution_input, execution_count) {
    invisible(.Call('_JuniperKernel_rebroadcast_input', PACKAGE = 'JuniperKernel', kernel, execution_input, execution_count))
}

execute_result <- function(kernel, data) {
    invisible(.Call('_JuniperKernel_execute_result', PACKAGE = 'JuniperKernel', kernel, data))
}

jk_device <- function(kernel, bg, width, height, pointsize, standalone, aliases) {
    invisible(.Call('_JuniperKernel_jk_device', PACKAGE = 'JuniperKernel', kernel, bg, width, height, pointsize, standalone, aliases))
}

filter_comms <- function(target_name) {
    .Call('_JuniperKernel_filter_comms', PACKAGE = 'JuniperKernel', target_name)
}

comm_request <- function(type) {
    invisible(.Call('_JuniperKernel_comm_request', PACKAGE = 'JuniperKernel', type))
}

run_client <- function(hbport, ioport, shport, ctport, inport) {
    .Call('_JuniperKernel_run_client', PACKAGE = 'JuniperKernel', hbport, ioport, shport, ctport, inport)
}

client_exec_request <- function(jtc, payload) {
    invisible(.Call('_JuniperKernel_client_exec_request', PACKAGE = 'JuniperKernel', jtc, payload))
}

client_exec_reply <- function(jtc) {
    .Call('_JuniperKernel_client_exec_reply', PACKAGE = 'JuniperKernel', jtc)
}

wait_for_hb <- function(jtc) {
    invisible(.Call('_JuniperKernel_wait_for_hb', PACKAGE = 'JuniperKernel', jtc))
}

iopub_recv <- function(jtc) {
    .Call('_JuniperKernel_iopub_recv', PACKAGE = 'JuniperKernel', jtc)
}

